exports.seed = function(knex) {
  return knex('language')
  .truncate()
  .then(() => {
    return knex('language').insert([
      { label: 'Abkhazian', code: 'ab' },
      { label: 'Afar', code: 'aa' },
      { label: 'Afrikaans', code: 'af' },
      { label: 'Akan', code: 'ak' },
      { label: 'Albanian', code: 'sq' },
      { label: 'Amharic', code: 'am' },
      { label: 'Arabic', code: 'ar' },
      { label: 'Aragonese', code: 'an' },
      { label: 'Armenian', code: 'hy' },
      { label: 'Assamese', code: 'as' },
      { label: 'Avaric', code: 'av' },
      { label: 'Avestan', code: 'ae' },
      { label: 'Aymara', code: 'ay' },
      { label: 'Azerbaijani', code: 'az' },
      { label: 'Bambara', code: 'bm' },
      { label: 'Bashkir', code: 'ba' },
      { label: 'Basque', code: 'eu' },
      { label: 'Belarusian', code: 'be' },
      { label: 'Bengali', code: 'bn' },
      { label: 'Bihari languages', code: 'bh' },
      { label: 'Bislama', code: 'bi' },
      { label: 'Bosnian', code: 'bs' },
      { label: 'Breton', code: 'br' },
      { label: 'Bulgarian', code: 'bg' },
      { label: 'Burmese', code: 'my' },
      { label: 'Catalan, Valencian', code: 'ca' },
      { label: 'Chamorro', code: 'ch' },
      { label: 'Chechen', code: 'ce' },
      { label: 'Chichewa, Chewa, Nyanja', code: 'ny' },
      { label: 'Chinese', code: 'zh' },
      { label: 'Chuvash', code: 'cv' },
      { label: 'Cornish', code: 'kw' },
      { label: 'Corsican', code: 'co' },
      { label: 'Cree', code: 'cr' },
      { label: 'Croatian', code: 'hr' },
      { label: 'Czech', code: 'cs' },
      { label: 'Danish', code: 'da' },
      { label: 'Divehi, Dhivehi, Maldivian', code: 'dv' },
      { label: 'Dutch, Flemish', code: 'nl' },
      { label: 'Dzongkha', code: 'dz' },
      { label: 'English', code: 'en' },
      { label: 'Esperanto', code: 'eo' },
      { label: 'Estonian', code: 'et' },
      { label: 'Ewe', code: 'ee' },
      { label: 'Faroese', code: 'fo' },
      { label: 'Fijian', code: 'fj' },
      { label: 'Finnish', code: 'fi' },
      { label: 'French', code: 'fr' },
      { label: 'Fulah', code: 'ff' },
      { label: 'Galician', code: 'gl' },
      { label: 'Georgian', code: 'ka' },
      { label: 'German', code: 'de' },
      { label: 'Greek, Modern (1453-)', code: 'el' },
      { label: 'Guarani', code: 'gn' },
      { label: 'Gujarati', code: 'gu' },
      { label: 'Haitian, Haitian Creole', code: 'ht' },
      { label: 'Hausa', code: 'ha' },
      { label: 'Hebrew', code: 'he' },
      { label: 'Herero', code: 'hz' },
      { label: 'Hindi', code: 'hi' },
      { label: 'Hiri Motu', code: 'ho' },
      { label: 'Hungarian', code: 'hu' },
      { label: 'Interlingua (International Auxiliary Language Association)', code: 'ia' },
      { label: 'Indonesian', code: 'id' },
      { label: 'Interlingue, Occidental', code: 'ie' },
      { label: 'Irish', code: 'ga' },
      { label: 'Igbo', code: 'ig' },
      { label: 'Inupiaq', code: 'ik' },
      { label: 'Ido', code: 'io' },
      { label: 'Icelandic', code: 'is' },
      { label: 'Italian', code: 'it' },
      { label: 'Inuktitut', code: 'iu' },
      { label: 'Japanese', code: 'ja' },
      { label: 'Javanese', code: 'jv' },
      { label: 'Kalaallisut, Greenlandic', code: 'kl' },
      { label: 'Kannada', code: 'kn' },
      { label: 'Kanuri', code: 'kr' },
      { label: 'Kashmiri', code: 'ks' },
      { label: 'Kazakh', code: 'kk' },
      { label: 'Central Khmer', code: 'km' },
      { label: 'Kikuyu, Gikuyu', code: 'ki' },
      { label: 'Kinyarwanda', code: 'rw' },
      { label: 'Kirghiz, Kyrgyz', code: 'ky' },
      { label: 'Komi', code: 'kv' },
      { label: 'Kongo', code: 'kg' },
      { label: 'Korean', code: 'ko' },
      { label: 'Kurdish', code: 'ku' },
      { label: 'Kuanyama, Kwanyama', code: 'kj' },
      { label: 'Latin', code: 'la' },
      { label: 'Luxembourgish, Letzeburgesch', code: 'lb' },
      { label: 'Ganda', code: 'lg' },
      { label: 'Limburgan, Limburger, Limburgish', code: 'li' },
      { label: 'Lingala', code: 'ln' },
      { label: 'Lao', code: 'lo' },
      { label: 'Lithuanian', code: 'lt' },
      { label: 'Luba-Katanga', code: 'lu' },
      { label: 'Latvian', code: 'lv' },
      { label: 'Manx', code: 'gv' },
      { label: 'Macedonian', code: 'mk' },
      { label: 'Malagasy', code: 'mg' },
      { label: 'Malay', code: 'ms' },
      { label: 'Malayalam', code: 'ml' },
      { label: 'Maltese', code: 'mt' },
      { label: 'Maori', code: 'mi' },
      { label: 'Marathi', code: 'mr' },
      { label: 'Marshallese', code: 'mh' },
      { label: 'Mongolian', code: 'mn' },
      { label: 'Nauru', code: 'na' },
      { label: 'Navajo, Navaho', code: 'nv' },
      { label: 'North Ndebele', code: 'nd' },
      { label: 'Nepali', code: 'ne' },
      { label: 'Ndonga', code: 'ng' },
      { label: 'Norwegian Bokmål', code: 'nb' },
      { label: 'Norwegian Nynorsk', code: 'nn' },
      { label: 'Norwegian', code: 'no' },
      { label: 'Sichuan Yi, Nuosu', code: 'ii' },
      { label: 'South Ndebele', code: 'nr' },
      { label: 'Occitan', code: 'oc' },
      { label: 'Ojibwa', code: 'oj' },
      { label: 'Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic', code: 'cu' },
      { label: 'Oromo', code: 'om' },
      { label: 'Oriya', code: 'or' },
      { label: 'Ossetian, Ossetic', code: 'os' },
      { label: 'Punjabi, Panjabi', code: 'pa' },
      { label: 'Pali', code: 'pi' },
      { label: 'Persian', code: 'fa' },
      { label: 'Polish', code: 'pl' },
      { label: 'Pashto, Pushto', code: 'ps' },
      { label: 'Portuguese', code: 'pt' },
      { label: 'Quechua', code: 'qu' },
      { label: 'Romansh', code: 'rm' },
      { label: 'Rundi', code: 'rn' },
      { label: 'Romanian, Moldavian, Moldovan', code: 'ro' },
      { label: 'Russian', code: 'ru' },
      { label: 'Sanskrit', code: 'sa' },
      { label: 'Sardinian', code: 'sc' },
      { label: 'Sindhi', code: 'sd' },
      { label: 'Northern Sami', code: 'se' },
      { label: 'Samoan', code: 'sm' },
      { label: 'Sango', code: 'sg' },
      { label: 'Serbian', code: 'sr' },
      { label: 'Gaelic, Scottish Gaelic', code: 'gd' },
      { label: 'Shona', code: 'sn' },
      { label: 'Sinhala, Sinhalese', code: 'si' },
      { label: 'Slovak', code: 'sk' },
      { label: 'Slovenian', code: 'sl' },
      { label: 'Somali', code: 'so' },
      { label: 'Southern Sotho', code: 'st' },
      { label: 'Spanish, Castilian', code: 'es' },
      { label: 'Sundanese', code: 'su' },
      { label: 'Swahili', code: 'sw' },
      { label: 'Swati', code: 'ss' },
      { label: 'Swedish', code: 'sv' },
      { label: 'Tamil', code: 'ta' },
      { label: 'Telugu', code: 'te' },
      { label: 'Tajik', code: 'tg' },
      { label: 'Thai', code: 'th' },
      { label: 'Tigrinya', code: 'ti' },
      { label: 'Tibetan', code: 'bo' },
      { label: 'Turkmen', code: 'tk' },
      { label: 'Tagalog', code: 'tl' },
      { label: 'Tswana', code: 'tn' },
      { label: 'Tonga (Tonga Islands)', code: 'to' },
      { label: 'Turkish', code: 'tr' },
      { label: 'Tsonga', code: 'ts' },
      { label: 'Tatar', code: 'tt' },
      { label: 'Twi', code: 'tw' },
      { label: 'Tahitian', code: 'ty' },
      { label: 'Uighur, Uyghur', code: 'ug' },
      { label: 'Ukrainian', code: 'uk' },
      { label: 'Urdu', code: 'ur' },
      { label: 'Uzbek', code: 'uz' },
      { label: 'Venda', code: 've' },
      { label: 'Vietnamese', code: 'vi' },
      { label: 'Volapük', code: 'vo' },
      { label: 'Walloon', code: 'wa' },
      { label: 'Welsh', code: 'cy' },
      { label: 'Wolof', code: 'wo' },
      { label: 'Western Frisian', code: 'fy' },
      { label: 'Xhosa', code: 'xh' },
      { label: 'Yiddish', code: 'yi' },
      { label: 'Yoruba', code: 'yo' },
      { label: 'Zhuang, Chuang', code: 'za' },
      { label: 'Zulu', code: 'zu' },
    ]);
  });
};
